{% set name = "pyasyncore" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyasyncore-{{ version }}.tar.gz
  sha256: 2c7a8b9b750ba6260f1e5a061456d61320a80579c6a43d42183417da89c7d5d6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.12,<3.13
    - pip
  run:
    - python >=3.12,<3.13

test:
  imports:
    - asyncore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/simonrob/pyasyncore
  summary: Make asyncore available for Python 3.12 onwards
  license: PSF-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
